// Generated by CoffeeScript 1.7.1
(function() {
  var deliveremail, dns, sendemail, simplesmtp, stream;

  simplesmtp = require('simplesmtp');

  stream = require('stream');

  dns = require('dns');

  deliveremail = function(to, from, host, stream, cb) {
    var client, sent;
    client = simplesmtp.connect(25, host, {
      greetingTimeout: 60 * 1000,
      connTimeout: 60 * 1000
    });
    sent = false;
    client.on('idle', function() {
      if (sent) {
        return client.quit();
      }
      client.useEnvelope({
        from: from,
        to: [to]
      });
      return sent = true;
    });
    client.on('rcptFailed', function(addresses) {
      return cb(new Error("Address rejected " + addresses[0]));
    });
    client.on('message', function() {
      return stream.pipe(client);
    });
    return client.on('ready', function(success, response) {
      if (!success) {
        return cb(new Error(response));
      }
      return cb(null, response);
    });
  };

  sendemail = function(to, from, stream, cb) {
    var host;
    host = to.split('@')[1];
    return dns.resolveMx(host, function(err, addresses) {
      var mail;
      if (err != null) {
        throw err;
      }
      if (addresses.length === 0) {
        return cb(new Error("No MX records for " + host));
      }
      addresses.sort(function(a, b) {
        if (a.priority >= b.priority) {
          return 1;
        } else {
          return -1;
        }
      });
      mail = addresses[0].exchange;
      return deliveremail(to, from, mail, stream, cb);
    });
  };

  module.exports = sendemail;

  module.exports.direct = deliveremail;

}).call(this);
