// Generated by CoffeeScript 1.7.1
(function() {
  var config, deliveremail, detail, details, display, dns, hostname, ip, moment, name, os, server, simplesmtp, stream, _i, _len, _ref,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  simplesmtp = require('simplesmtp');

  stream = require('stream');

  moment = require('moment');

  os = require('os');

  require('colors');

  config = require('./config.json');

  deliveremail = require('./deliveremail');

  dns = require('dns');

  server = simplesmtp.createServer();

  server.listen(25);

  ip = '127.0.0.1';

  _ref = os.networkInterfaces();
  for (name in _ref) {
    details = _ref[name];
    for (_i = 0, _len = details.length; _i < _len; _i++) {
      detail = details[_i];
      if (detail.family === 'IPv4' && !detail.internal) {
        ip = detail.address;
      }
    }
  }

  hostname = os.hostname();

  console.log();

  console.log(("   Pokemon Emails listening on port 25 at " + ip).cyan);

  console.log();

  display = function(success, conn, err) {
    var msg;
    msg = "From:  " + conn.from + "\n   To:    " + conn.to;
    if (conn.forwardto != null) {
      msg += "\n   Proxy: " + conn.forwardto;
    }
    if (conn.remoteDNS != null) {
      msg += "\n   Host:  " + conn.remoteDNS;
    }
    if (success) {
      return console.log((" √ " + msg + "\n").green);
    }
    console.error((" X " + msg).red);
    if (err != null) {
      console.error(("   Error: " + err).red);
    }
    return console.error();
  };

  server.on('startData', function(conn) {
    var host, to, _j, _len1, _ref1;
    if (conn.to.length !== 1) {
      return conn.deny = true;
    }
    _ref1 = conn.to;
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      to = _ref1[_j];
      host = to.split('@')[1];
      if (!(__indexOf.call(config.hosts, host) >= 0)) {
        return conn.deny = true;
      }
    }
    conn.forwardto = config.forwardto;
    conn.saveStream = new stream.PassThrough();
    return dns.reverse(conn.remoteAddress, function(err, domains) {
      var domain;
      if ((err == null) && domains.length > 0) {
        domain = domains[0];
        conn.remoteDNS = domain;
        conn.saveStream.write("Received: from " + domain + " ([" + conn.remoteAddress + "]) by " + hostname + " with SMTP id generated;\r\n");
      } else {
        conn.saveStream.write("Received: by " + hostname + " with SMTP id generated;\r\n");
      }
      conn.saveStream.write("        " + (moment().format('ddd, DD MMM YYYY HH:mm:ss ZZ')) + " (UTC)\r\n");
      return deliveremail(conn.forwardto, conn.from, conn.saveStream, function(err, message) {
        if (err == null) {
          display(true, conn);
        } else {
          display(false, conn, err);
        }
        return conn.cb(err, message);
      });
    });
  });

  server.on('data', function(conn, chunk) {
    if ((conn.deny != null) && conn.deny) {
      return;
    }
    return conn.saveStream.write(chunk);
  });

  server.on('dataReady', function(conn, cb) {
    if ((conn.deny != null) && conn.deny) {
      display(false, conn, 'proxy denied');
      return cb(new Error('denied'));
    }
    conn.saveStream.end();
    return conn.cb = cb;
  });

}).call(this);
